---
# tasks file for docker-registry.
- name: Log into DockerHub
  docker_login:
    username: skander123
    password: Sk20334951
    
#- name: Tag and push to docker hub
#  docker_image:
#    name: mypipeline
#    repository: mohamedmselmi/mypipeline
#    tag: 7.0
#    push: yes
#    source: local
    
- name: Tag and push to docker hub
  community.docker.docker_image:
     name: livraisoncontinue:latest
     repository: devops/livraisoncontinue:1.2
     push: yes
     source: local
